/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesIdRouteImport } from './routes/admin/articles/$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminPortfolioIndexRouteImport } from './routes/admin/portfolio/index'
import { Route as AdminPortfolioIdRouteImport } from './routes/admin/portfolio/$id'
import { Route as AdminPortfolioNewRouteImport } from './routes/admin/portfolio/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/admin/articles/$id',
  path: '/admin/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/admin/articles/new',
  path: '/admin/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortfolioIndexRoute = AdminPortfolioIndexRouteImport.update({
  id: '/admin/portfolio/',
  path: '/admin/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortfolioIdRoute = AdminPortfolioIdRouteImport.update({
  id: '/admin/portfolio/$id',
  path: '/admin/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortfolioNewRoute = AdminPortfolioNewRouteImport.update({
  id: '/admin/portfolio/new',
  path: '/admin/portfolio/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/portfolio/new': typeof AdminPortfolioNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/portfolio/': typeof AdminPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/portfolio/new': typeof AdminPortfolioNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/portfolio': typeof AdminPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/portfolio/new': typeof AdminPortfolioNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/portfolio/': typeof AdminPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/login'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/portfolio/'
    | '/services/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/portfolio/$id'
    | '/admin/portfolio/new'
    | '/admin/articles/'
    | '/admin/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/login'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin'
    | '/blog'
    | '/portfolio'
    | '/services'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/portfolio/$id'
    | '/admin/portfolio/new'
    | '/admin/articles'
    | '/admin/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/login'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/portfolio/'
    | '/services/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/portfolio/$id'
    | '/admin/portfolio/new'
    | '/admin/articles/'
    | '/admin/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminPortfolioIdRoute: typeof AdminPortfolioIdRoute
  AdminPortfolioNewRoute: typeof AdminPortfolioNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminPortfolioIndexRoute: typeof AdminPortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/admin/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/admin/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/portfolio/': {
      id: '/admin/portfolio/'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio/'
      preLoaderRoute: typeof AdminPortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/portfolio/$id': {
      id: '/admin/portfolio/$id'
      path: '/admin/portfolio/$id'
      fullPath: '/admin/portfolio/$id'
      preLoaderRoute: typeof AdminPortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/portfolio/new': {
      id: '/admin/portfolio/new'
      path: '/admin/portfolio/new'
      fullPath: '/admin/portfolio/new'
      preLoaderRoute: typeof AdminPortfolioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminPortfolioIdRoute: AdminPortfolioIdRoute,
  AdminPortfolioNewRoute: AdminPortfolioNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminPortfolioIndexRoute: AdminPortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
